apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
  namespace: ecommerce
spec:
  capacity:
    storage: 10Gi # Adjusted to match the PVC request
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual # Ensure this matches the PVC
  hostPath:
    path: "/mnt/data"
