apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp2-storage-class
  namespace: ecommerce
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2 # General Purpose SSD (gp2)
  fsType: ext4
reclaimPolicy: Retain # Specify whether to retain or delete the volume when PVC is deleted
